export const SELECTTEMPLATE = "SELECTTEMPLATE";
export const SELECTRESUME = "SELECTRESUME";
export const ADDPERSONALINFO = "ADDPERSONALINFO";
export const ADDEXPERIENCE = "ADDEXPERIENCE";
export const ADDALLEXPERIENCE = "ADDALLEXPERIENCE";
export const REMOVEEXPERIENCE = "REMOVEEXPERIENCE";
export const ADDNEWSKILLS = "ADDNEWSKILLS";
export const EDITSKILL = "EDITSKILL";
export const DELETESKILL = "DELETESKILL";
export const ADDEDUCATION = "ADDEDUCATION";
export const ADDALLEDUCATION="ADDALLEDUCATION"

// New action types for Projects, Certifications, and Achievements
export const ADDPROJECT = "ADDPROJECT";
export const ADDALLPROJECTS = "ADDALLPROJECTS";

export const ADDCERTIFICATION = "ADDCERTIFICATION";
export const ADDALLCERTIFICATIONS = "ADDALLCERTIFICATIONS";

export const ADDACHIEVEMENT = "ADDACHIEVEMENT";
export const ADDALLACHIEVEMENTS = "ADDALLACHIEVEMENTS";
// export const EDITACHIEVEMENT = "EDITACHIEVEMENT";
// export const DELETEACHIEVEMENT = "DELETEACHIEVEMENT";
